//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.19 at 03:12:50 PM EDT 
//


package com.semantic.safetycheck.client.weather;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="credit_URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="image" type="{}imageType" minOccurs="0"/>
 *         &lt;element name="suggested_pickup" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="suggested_pickup_period" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="station_id" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="elevation" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="observation_time" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="observation_time_rfc822" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="weather" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="temperature_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="temp_f" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="temp_c" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="water_temp_f" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="water_temp_c" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="relative_humidity" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="wind_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="wind_dir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="wind_degrees" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="wind_mph" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="wind_gust_mph" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="wind_kt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="wind_gust_kt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="pressure_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="pressure_mb" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="pressure_in" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="pressure_tendency_mb" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="pressure_tendency_in" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="dewpoint_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="dewpoint_f" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="dewpoint_c" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="heat_index_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="heat_index_f" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="heat_index_c" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="windchill_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="windchill_f" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="windchill_c" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="visibility_mi" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="wave_height_m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="wave_height_ft" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="dominant_period_sec" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="average_period_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="mean_wave_dir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mean_wave_degrees" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="tide_ft" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="steepness" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="water_column_height" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="surf_height_ft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="swell_dir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="swell_degrees" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="swell_period" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="icon_url_base" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="icon_name" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="two_day_history_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="icon_url_name" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ob_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="disclaimer_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="copyright_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="privacy_policy_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" default="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "credit",
    "creditURL",
    "image",
    "suggestedPickup",
    "suggestedPickupPeriod",
    "location",
    "stationId",
    "latitude",
    "longitude",
    "elevation",
    "observationTime",
    "observationTimeRfc822",
    "weather",
    "temperatureString",
    "tempF",
    "tempC",
    "waterTempF",
    "waterTempC",
    "relativeHumidity",
    "windString",
    "windDir",
    "windDegrees",
    "windMph",
    "windGustMph",
    "windKt",
    "windGustKt",
    "pressureString",
    "pressureMb",
    "pressureIn",
    "pressureTendencyMb",
    "pressureTendencyIn",
    "dewpointString",
    "dewpointF",
    "dewpointC",
    "heatIndexString",
    "heatIndexF",
    "heatIndexC",
    "windchillString",
    "windchillF",
    "windchillC",
    "visibilityMi",
    "waveHeightM",
    "waveHeightFt",
    "dominantPeriodSec",
    "averagePeriodSec",
    "meanWaveDir",
    "meanWaveDegrees",
    "tideFt",
    "steepness",
    "waterColumnHeight",
    "surfHeightFt",
    "swellDir",
    "swellDegrees",
    "swellPeriod",
    "iconUrlBase",
    "iconName",
    "twoDayHistoryUrl",
    "iconUrlName",
    "obUrl",
    "disclaimerUrl",
    "copyrightUrl",
    "privacyPolicyUrl"
})
@XmlRootElement(name = "current_observation")
public class CurrentObservation {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String credit;
    @XmlElement(name = "credit_URL")
    @XmlSchemaType(name = "anyURI")
    protected String creditURL;
    protected ImageType image;
    @XmlElement(name = "suggested_pickup")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String suggestedPickup;
    @XmlElement(name = "suggested_pickup_period")
    protected BigInteger suggestedPickupPeriod;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String location;
    @XmlElement(name = "station_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String stationId;
    protected String latitude;
    protected String longitude;
    protected BigInteger elevation;
    @XmlElement(name = "observation_time")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String observationTime;
    @XmlElement(name = "observation_time_rfc822")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String observationTimeRfc822;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String weather;
    @XmlElement(name = "temperature_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String temperatureString;
    @XmlElement(name = "temp_f")
    protected BigDecimal tempF;
    @XmlElement(name = "temp_c")
    protected BigDecimal tempC;
    @XmlElement(name = "water_temp_f")
    protected BigDecimal waterTempF;
    @XmlElement(name = "water_temp_c")
    protected BigDecimal waterTempC;
    @XmlElement(name = "relative_humidity")
    protected BigInteger relativeHumidity;
    @XmlElement(name = "wind_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String windString;
    @XmlElement(name = "wind_dir")
    protected String windDir;
    @XmlElement(name = "wind_degrees")
    protected BigInteger windDegrees;
    @XmlElement(name = "wind_mph")
    protected BigDecimal windMph;
    @XmlElement(name = "wind_gust_mph")
    protected BigDecimal windGustMph;
    @XmlElement(name = "wind_kt")
    protected BigDecimal windKt;
    @XmlElement(name = "wind_gust_kt")
    protected BigDecimal windGustKt;
    @XmlElement(name = "pressure_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String pressureString;
    @XmlElement(name = "pressure_mb")
    protected BigDecimal pressureMb;
    @XmlElement(name = "pressure_in")
    protected BigDecimal pressureIn;
    @XmlElement(name = "pressure_tendency_mb")
    protected BigDecimal pressureTendencyMb;
    @XmlElement(name = "pressure_tendency_in")
    protected BigDecimal pressureTendencyIn;
    @XmlElement(name = "dewpoint_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String dewpointString;
    @XmlElement(name = "dewpoint_f")
    protected BigDecimal dewpointF;
    @XmlElement(name = "dewpoint_c")
    protected BigDecimal dewpointC;
    @XmlElement(name = "heat_index_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String heatIndexString;
    @XmlElement(name = "heat_index_f")
    protected BigInteger heatIndexF;
    @XmlElement(name = "heat_index_c")
    protected BigInteger heatIndexC;
    @XmlElement(name = "windchill_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String windchillString;
    @XmlElement(name = "windchill_f")
    protected BigInteger windchillF;
    @XmlElement(name = "windchill_c")
    protected BigInteger windchillC;
    @XmlElement(name = "visibility_mi")
    protected BigDecimal visibilityMi;
    @XmlElement(name = "wave_height_m")
    protected BigDecimal waveHeightM;
    @XmlElement(name = "wave_height_ft")
    protected BigDecimal waveHeightFt;
    @XmlElement(name = "dominant_period_sec")
    protected BigInteger dominantPeriodSec;
    @XmlElement(name = "average_period_sec")
    protected BigDecimal averagePeriodSec;
    @XmlElement(name = "mean_wave_dir")
    protected String meanWaveDir;
    @XmlElement(name = "mean_wave_degrees")
    protected BigInteger meanWaveDegrees;
    @XmlElement(name = "tide_ft")
    protected BigDecimal tideFt;
    protected String steepness;
    @XmlElement(name = "water_column_height")
    protected BigDecimal waterColumnHeight;
    @XmlElement(name = "surf_height_ft")
    protected String surfHeightFt;
    @XmlElement(name = "swell_dir")
    protected String swellDir;
    @XmlElement(name = "swell_degrees")
    protected BigInteger swellDegrees;
    @XmlElement(name = "swell_period")
    protected String swellPeriod;
    @XmlElement(name = "icon_url_base")
    @XmlSchemaType(name = "anyURI")
    protected String iconUrlBase;
    @XmlElement(name = "icon_name")
    @XmlSchemaType(name = "anyURI")
    protected String iconName;
    @XmlElement(name = "two_day_history_url")
    @XmlSchemaType(name = "anyURI")
    protected String twoDayHistoryUrl;
    @XmlElement(name = "icon_url_name")
    @XmlSchemaType(name = "anyURI")
    protected String iconUrlName;
    @XmlElement(name = "ob_url")
    @XmlSchemaType(name = "anyURI")
    protected String obUrl;
    @XmlElement(name = "disclaimer_url")
    @XmlSchemaType(name = "anyURI")
    protected String disclaimerUrl;
    @XmlElement(name = "copyright_url")
    @XmlSchemaType(name = "anyURI")
    protected String copyrightUrl;
    @XmlElement(name = "privacy_policy_url")
    @XmlSchemaType(name = "anyURI")
    protected String privacyPolicyUrl;
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the credit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredit(String value) {
        this.credit = value;
    }

    /**
     * Gets the value of the creditURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditURL() {
        return creditURL;
    }

    /**
     * Sets the value of the creditURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditURL(String value) {
        this.creditURL = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link ImageType }
     *     
     */
    public ImageType getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageType }
     *     
     */
    public void setImage(ImageType value) {
        this.image = value;
    }

    /**
     * Gets the value of the suggestedPickup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuggestedPickup() {
        return suggestedPickup;
    }

    /**
     * Sets the value of the suggestedPickup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuggestedPickup(String value) {
        this.suggestedPickup = value;
    }

    /**
     * Gets the value of the suggestedPickupPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSuggestedPickupPeriod() {
        return suggestedPickupPeriod;
    }

    /**
     * Sets the value of the suggestedPickupPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSuggestedPickupPeriod(BigInteger value) {
        this.suggestedPickupPeriod = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the stationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * Sets the value of the stationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationId(String value) {
        this.stationId = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitude(String value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitude(String value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setElevation(BigInteger value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the observationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationTime() {
        return observationTime;
    }

    /**
     * Sets the value of the observationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationTime(String value) {
        this.observationTime = value;
    }

    /**
     * Gets the value of the observationTimeRfc822 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationTimeRfc822() {
        return observationTimeRfc822;
    }

    /**
     * Sets the value of the observationTimeRfc822 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationTimeRfc822(String value) {
        this.observationTimeRfc822 = value;
    }

    /**
     * Gets the value of the weather property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeather() {
        return weather;
    }

    /**
     * Sets the value of the weather property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeather(String value) {
        this.weather = value;
    }

    /**
     * Gets the value of the temperatureString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureString() {
        return temperatureString;
    }

    /**
     * Sets the value of the temperatureString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureString(String value) {
        this.temperatureString = value;
    }

    /**
     * Gets the value of the tempF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTempF() {
        return tempF;
    }

    /**
     * Sets the value of the tempF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTempF(BigDecimal value) {
        this.tempF = value;
    }

    /**
     * Gets the value of the tempC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTempC() {
        return tempC;
    }

    /**
     * Sets the value of the tempC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTempC(BigDecimal value) {
        this.tempC = value;
    }

    /**
     * Gets the value of the waterTempF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaterTempF() {
        return waterTempF;
    }

    /**
     * Sets the value of the waterTempF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaterTempF(BigDecimal value) {
        this.waterTempF = value;
    }

    /**
     * Gets the value of the waterTempC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaterTempC() {
        return waterTempC;
    }

    /**
     * Sets the value of the waterTempC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaterTempC(BigDecimal value) {
        this.waterTempC = value;
    }

    /**
     * Gets the value of the relativeHumidity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRelativeHumidity() {
        return relativeHumidity;
    }

    /**
     * Sets the value of the relativeHumidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRelativeHumidity(BigInteger value) {
        this.relativeHumidity = value;
    }

    /**
     * Gets the value of the windString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindString() {
        return windString;
    }

    /**
     * Sets the value of the windString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindString(String value) {
        this.windString = value;
    }

    /**
     * Gets the value of the windDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindDir() {
        return windDir;
    }

    /**
     * Sets the value of the windDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindDir(String value) {
        this.windDir = value;
    }

    /**
     * Gets the value of the windDegrees property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWindDegrees() {
        return windDegrees;
    }

    /**
     * Sets the value of the windDegrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWindDegrees(BigInteger value) {
        this.windDegrees = value;
    }

    /**
     * Gets the value of the windMph property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWindMph() {
        return windMph;
    }

    /**
     * Sets the value of the windMph property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWindMph(BigDecimal value) {
        this.windMph = value;
    }

    /**
     * Gets the value of the windGustMph property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWindGustMph() {
        return windGustMph;
    }

    /**
     * Sets the value of the windGustMph property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWindGustMph(BigDecimal value) {
        this.windGustMph = value;
    }

    /**
     * Gets the value of the windKt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWindKt() {
        return windKt;
    }

    /**
     * Sets the value of the windKt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWindKt(BigDecimal value) {
        this.windKt = value;
    }

    /**
     * Gets the value of the windGustKt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWindGustKt() {
        return windGustKt;
    }

    /**
     * Sets the value of the windGustKt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWindGustKt(BigDecimal value) {
        this.windGustKt = value;
    }

    /**
     * Gets the value of the pressureString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPressureString() {
        return pressureString;
    }

    /**
     * Sets the value of the pressureString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPressureString(String value) {
        this.pressureString = value;
    }

    /**
     * Gets the value of the pressureMb property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPressureMb() {
        return pressureMb;
    }

    /**
     * Sets the value of the pressureMb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPressureMb(BigDecimal value) {
        this.pressureMb = value;
    }

    /**
     * Gets the value of the pressureIn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPressureIn() {
        return pressureIn;
    }

    /**
     * Sets the value of the pressureIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPressureIn(BigDecimal value) {
        this.pressureIn = value;
    }

    /**
     * Gets the value of the pressureTendencyMb property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPressureTendencyMb() {
        return pressureTendencyMb;
    }

    /**
     * Sets the value of the pressureTendencyMb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPressureTendencyMb(BigDecimal value) {
        this.pressureTendencyMb = value;
    }

    /**
     * Gets the value of the pressureTendencyIn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPressureTendencyIn() {
        return pressureTendencyIn;
    }

    /**
     * Sets the value of the pressureTendencyIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPressureTendencyIn(BigDecimal value) {
        this.pressureTendencyIn = value;
    }

    /**
     * Gets the value of the dewpointString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDewpointString() {
        return dewpointString;
    }

    /**
     * Sets the value of the dewpointString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDewpointString(String value) {
        this.dewpointString = value;
    }

    /**
     * Gets the value of the dewpointF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDewpointF() {
        return dewpointF;
    }

    /**
     * Sets the value of the dewpointF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDewpointF(BigDecimal value) {
        this.dewpointF = value;
    }

    /**
     * Gets the value of the dewpointC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDewpointC() {
        return dewpointC;
    }

    /**
     * Sets the value of the dewpointC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDewpointC(BigDecimal value) {
        this.dewpointC = value;
    }

    /**
     * Gets the value of the heatIndexString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeatIndexString() {
        return heatIndexString;
    }

    /**
     * Sets the value of the heatIndexString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeatIndexString(String value) {
        this.heatIndexString = value;
    }

    /**
     * Gets the value of the heatIndexF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeatIndexF() {
        return heatIndexF;
    }

    /**
     * Sets the value of the heatIndexF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeatIndexF(BigInteger value) {
        this.heatIndexF = value;
    }

    /**
     * Gets the value of the heatIndexC property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeatIndexC() {
        return heatIndexC;
    }

    /**
     * Sets the value of the heatIndexC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeatIndexC(BigInteger value) {
        this.heatIndexC = value;
    }

    /**
     * Gets the value of the windchillString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindchillString() {
        return windchillString;
    }

    /**
     * Sets the value of the windchillString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindchillString(String value) {
        this.windchillString = value;
    }

    /**
     * Gets the value of the windchillF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWindchillF() {
        return windchillF;
    }

    /**
     * Sets the value of the windchillF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWindchillF(BigInteger value) {
        this.windchillF = value;
    }

    /**
     * Gets the value of the windchillC property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWindchillC() {
        return windchillC;
    }

    /**
     * Sets the value of the windchillC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWindchillC(BigInteger value) {
        this.windchillC = value;
    }

    /**
     * Gets the value of the visibilityMi property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVisibilityMi() {
        return visibilityMi;
    }

    /**
     * Sets the value of the visibilityMi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVisibilityMi(BigDecimal value) {
        this.visibilityMi = value;
    }

    /**
     * Gets the value of the waveHeightM property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaveHeightM() {
        return waveHeightM;
    }

    /**
     * Sets the value of the waveHeightM property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaveHeightM(BigDecimal value) {
        this.waveHeightM = value;
    }

    /**
     * Gets the value of the waveHeightFt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaveHeightFt() {
        return waveHeightFt;
    }

    /**
     * Sets the value of the waveHeightFt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaveHeightFt(BigDecimal value) {
        this.waveHeightFt = value;
    }

    /**
     * Gets the value of the dominantPeriodSec property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDominantPeriodSec() {
        return dominantPeriodSec;
    }

    /**
     * Sets the value of the dominantPeriodSec property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDominantPeriodSec(BigInteger value) {
        this.dominantPeriodSec = value;
    }

    /**
     * Gets the value of the averagePeriodSec property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAveragePeriodSec() {
        return averagePeriodSec;
    }

    /**
     * Sets the value of the averagePeriodSec property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAveragePeriodSec(BigDecimal value) {
        this.averagePeriodSec = value;
    }

    /**
     * Gets the value of the meanWaveDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeanWaveDir() {
        return meanWaveDir;
    }

    /**
     * Sets the value of the meanWaveDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeanWaveDir(String value) {
        this.meanWaveDir = value;
    }

    /**
     * Gets the value of the meanWaveDegrees property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMeanWaveDegrees() {
        return meanWaveDegrees;
    }

    /**
     * Sets the value of the meanWaveDegrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMeanWaveDegrees(BigInteger value) {
        this.meanWaveDegrees = value;
    }

    /**
     * Gets the value of the tideFt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTideFt() {
        return tideFt;
    }

    /**
     * Sets the value of the tideFt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTideFt(BigDecimal value) {
        this.tideFt = value;
    }

    /**
     * Gets the value of the steepness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSteepness() {
        return steepness;
    }

    /**
     * Sets the value of the steepness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSteepness(String value) {
        this.steepness = value;
    }

    /**
     * Gets the value of the waterColumnHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaterColumnHeight() {
        return waterColumnHeight;
    }

    /**
     * Sets the value of the waterColumnHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaterColumnHeight(BigDecimal value) {
        this.waterColumnHeight = value;
    }

    /**
     * Gets the value of the surfHeightFt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurfHeightFt() {
        return surfHeightFt;
    }

    /**
     * Sets the value of the surfHeightFt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurfHeightFt(String value) {
        this.surfHeightFt = value;
    }

    /**
     * Gets the value of the swellDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwellDir() {
        return swellDir;
    }

    /**
     * Sets the value of the swellDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwellDir(String value) {
        this.swellDir = value;
    }

    /**
     * Gets the value of the swellDegrees property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSwellDegrees() {
        return swellDegrees;
    }

    /**
     * Sets the value of the swellDegrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSwellDegrees(BigInteger value) {
        this.swellDegrees = value;
    }

    /**
     * Gets the value of the swellPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwellPeriod() {
        return swellPeriod;
    }

    /**
     * Sets the value of the swellPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwellPeriod(String value) {
        this.swellPeriod = value;
    }

    /**
     * Gets the value of the iconUrlBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconUrlBase() {
        return iconUrlBase;
    }

    /**
     * Sets the value of the iconUrlBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconUrlBase(String value) {
        this.iconUrlBase = value;
    }

    /**
     * Gets the value of the iconName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconName() {
        return iconName;
    }

    /**
     * Sets the value of the iconName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconName(String value) {
        this.iconName = value;
    }

    /**
     * Gets the value of the twoDayHistoryUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwoDayHistoryUrl() {
        return twoDayHistoryUrl;
    }

    /**
     * Sets the value of the twoDayHistoryUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwoDayHistoryUrl(String value) {
        this.twoDayHistoryUrl = value;
    }

    /**
     * Gets the value of the iconUrlName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconUrlName() {
        return iconUrlName;
    }

    /**
     * Sets the value of the iconUrlName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconUrlName(String value) {
        this.iconUrlName = value;
    }

    /**
     * Gets the value of the obUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObUrl() {
        return obUrl;
    }

    /**
     * Sets the value of the obUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObUrl(String value) {
        this.obUrl = value;
    }

    /**
     * Gets the value of the disclaimerUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimerUrl() {
        return disclaimerUrl;
    }

    /**
     * Sets the value of the disclaimerUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimerUrl(String value) {
        this.disclaimerUrl = value;
    }

    /**
     * Gets the value of the copyrightUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyrightUrl() {
        return copyrightUrl;
    }

    /**
     * Sets the value of the copyrightUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyrightUrl(String value) {
        this.copyrightUrl = value;
    }

    /**
     * Gets the value of the privacyPolicyUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacyPolicyUrl() {
        return privacyPolicyUrl;
    }

    /**
     * Sets the value of the privacyPolicyUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacyPolicyUrl(String value) {
        this.privacyPolicyUrl = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
